name: Scheduled v4 Optimization
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    container:
      image: fedora:43

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Tools
        run: dnf install -y rpm-build rpmspectool dnf-plugins-core gcc make createrepo_c git python3

      - name: Run Hit List Check
        id: scanner
        run: |
          UPDATES=$(python3 check_updates.py | grep "Triggering build for:" | sed 's/Triggering build for: //')
          echo "packages=$UPDATES" >> $GITHUB_OUTPUT

      - name: Build Outdated Packages
        if: steps.scanner.outputs.packages != ''
        run: |
          PKGS=$(echo "${{ steps.scanner.outputs.packages }}" | tr -d "[]'," )

          for pkg in $PKGS; do
            echo "--- Processing $pkg ---"
            dnf download --source $pkg
            dnf builddep -y $pkg-*.src.rpm

            mkdir -p bin_output

            rpm -ivh $pkg-*.src.rpm

            sed -i '1i %global optflags %{optflags} -march=znver4 -mtune=znver4' ~/rpmbuild/SPECS/*.spec

            rpmbuild -bb ~/rpmbuild/SPECS/*.spec \
              --nocheck \
              --define "_rpmdir $(pwd)/bin_output" \
              --define "debug_package %{nil}" \
              --define "_annotated_build 0"

              cp bin_output/x86_64/*.rpm ./x86_64/
              rm -rf bin_output/* $pkg-*.src.rpm
            done

      - name: Deploy to GitHub Pages
        if: steps.scanner.outputs.packages != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          createrepo_c ./x86_64/
          git add x86_64/
          git commit -m "Automated v4 update: ${{ steps.scanner.outputs.packages }}"
          git push
